### ISSUE TITLE
🦠 Model Request: cool molecule

### ISSUE THREAD

**Issue by GrantBirki** [GrantBirki/actions-sandbox#4]
### Model Name

my cool molecule

### Model Description

This is a prediction for a super cool molecule

### Ersilia ID

eos00ab

### Publication

The following link is just an example:

www.example.com

**Comment by GrantBirki** [comment]
test

**Comment by GrantBirki** [comment]
Created repository [](https://github.com/birki-io/eos11aa) ✨

**Comment by GrantBirki** [comment]
Created repository [birki-io/eos11aa](https://github.com/birki-io/eos11aa) ✨

**Comment by miquelduranfrigola** [comment]
Amazing! Anything you need on my end here?

**Comment by GrantBirki** [comment]
Created repository [birki-io/eos00ab](https://github.com/birki-io/eos00ab) ✨
